trigger:
  tags:
    include:
    - "*"
  branches:
    include:
    - feature/*
pr:
- main

pool:
  name: Default

steps:
- script: |
    echo $(Build.BuildReason)
    echo $(Build.SourceBranchName)
    echo $(Build.SourceBranch)