trigger:
  tags:
    include:
    - "*"
  branches:
    include:
    - main
    - feature/*
pr:
- main

pool:
  name: Default

steps:

- script: |
    echo $(Build.Reason)
    echo $(Build.SourceBranchName)
    echo $(Build.SourceBranch)


# If it's a PR or a build from main (not a tag) then don't publish to Nuget
- ${{ if or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
  script: |
    echo "this is a PR Build - no nuget"
- ${{ else }}:
  script: |
    echo "this is a feature or tag build - push nuget"