trigger:
  tags:
    include:
    - "*"
  branches:
    include:
    - feature/*
pr:
- main

pool:
  name: Default

steps:
- pwsh: |
    Write-Host "$(Build.BuildReason)"
    Write-Host "$(Build.SourceBranchName)" 
    Write-Host "$(Build.SourceBranch)"